# Generated by Django 5.0.6 on 2024-05-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='location',
        ),
        migrations.AddField(
            model_name='memory',
            name='latitude',
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='longitude',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
    ]
